### ISSUE TITLE
Missing resultTypes in typings/docs

### ISSUE THREAD

**Issue by Teomik129** [feathersjs-ecosystem/batch-loader#14]
The docs and types for batch-loader indicate '', '!', and '[]' as possible result types. However, it looks like the [source itself](https://github.com/feathers-plus/batch-loader/blob/e22aaaac8766f6b35bbfe19718f928106521ca50/lib/index.js#L4) actually accepts all of the following:
- ''
- '!'
- '[]'
- '[]!'
- '[!]!'

Could the types and docs be updated to reflect this?

**Comment by DaddyWarbucks** [comment]
Fixed. Thanks!
