### ISSUE TITLE
Missing docs / dead links

### ISSUE THREAD

**Issue by BengtHagemeister** [feathersjs-ecosystem/batch-loader#16]
Hi,

I was looking for the guide / docs and it seems that the docs for the batch-loader are dead because github pages does not work when a repo is archived (https://github.com/feathers-plus/docs).

Dead link:
https://github.com/feathersjs-ecosystem/batch-loader/blob/e22aaaac8766f6b35bbfe19718f928106521ca50/README.md#L19

https://feathers-plus.github.io/v1/batch-loader/guide.html

Are there any plans on migrating the docs repo to the feathersjs-ecosystem organisation?

Is contribution welcome to intergrate the batch-loader docs into this respository (/docs folder) and create a github page from this repo?

**Comment by DaddyWarbucks** [comment]
There are plans to migrate the contents of this repo over to the feathersjs-ecosystem organization. Possibly a rename and general update as well. But, we are not quite sure when that is happening. The original maintainer of this repo is no longer active and there was also a recent update to `feathers-batch`, so this repo was archived to avoid confusion. 

If you have any questions until then, feel free to give me (Beau Shaw) a shout over in the Feathers Slack channel and I would be happy to help. I use, and will continue to use, this code in many projects. So even with a name change and some updates you are safe to use this code in production IMHO.

**Comment by DaddyWarbucks** [comment]
@BengtHagemeister You can also use the WaybackMachine as a holdover until we do get this updated.
https://web.archive.org/web/20181014000938/https://feathers-plus.github.io/v1/batch-loader/guide.html

**Comment by BengtHagemeister** [comment]
Thanks for your quick answer!

> there was also a recent update to `feathers-batch`, so this repo was archived to avoid confusion.

Will feathers-batch be a replacement for batch-loader? In my understanding they solve quite a different problem.

**Comment by MarcGodard** [comment]
Should we not use this anymore?

**Comment by DaddyWarbucks** [comment]
feathers-batch does not replace this library. They are complimentary.

And yes. You should definitely still use this. It has been moved over to the feathers-ecosystem. It is in need of some documentation updates and general upkeep. But I use this in many production apps and will continue to do so. I will try to make some time this week to update the docs.

**Comment by DaddyWarbucks** [comment]
The repo now contains a `docs` directory and should hold what you guys are looking for.
